services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order_tracker
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d order_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  # test db
  postgres_test_init:
    image: postgres:17
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGUSER: admin
      PGPASSWORD: admin
      PGDATABASE: order_tracker
    command: >
      psql -c "CREATE DATABASE order_tracker_test;"

volumes:
  postgres_data: